"""
output_guardrail.py — Post-processes LLM responses to block investment advice and unsafe recommendations.
Replaces prohibited advisory statements with standardized compliance warnings.
"""
from __future__ import annotations

import logging
import re

logger = logging.getLogger(__name__)


class OutputGuardrail:
    """Monitors generated responses for financial advice violations and hallucinated recommendations."""

    def __init__(self) -> None:
        # Map unsafe phrases to standardized disclaimer replacements
        self._prohibited_phrases = {
            r"(?i)\bbuy\s+this\s+stock\s+now\b": "This information is for educational purposes and should not be considered financial advice.",
            r"(?i)\bstrong\s+buy\b": "This information is for educational purposes and should not be considered financial advice.",
            r"(?i)\bi\s+recommend\s+buying\b": "This information is for educational purposes and should not be considered financial advice.",
            r"(?i)\bi\s+suggest\s+buying\b": "This information is for educational purposes and should not be considered financial advice.",
            r"(?i)\byou\s+should\s+invest\b": "This information is for educational purposes and should not be considered financial advice.",
            r"(?i)\byou\s+must\s+buy\b": "This information is for educational purposes and should not be considered financial advice.",
            r"(?i)\bbuy\s+recommendation\b": "This information is for educational purposes and should not be considered financial advice."
        }

    def evaluate(self, answer: str) -> str:
        """
        Scan and sanitize the generated response to block investment advice.
        
        Args:
            answer: Raw text response generated by the LLM.
            
        Returns:
            Sanitized answer with compliant replacements.
        """
        logger.info("OutputGuardrail: Evaluating LLM answer for compliance...")
        sanitized = answer

        # Apply regex-based replacements for advice violations
        for pattern, replacement in self._prohibited_phrases.items():
            if re.search(pattern, sanitized):
                logger.warning("OutputGuardrail: Flagged unsafe investment advice pattern: %r", pattern)
                sanitized = re.sub(pattern, replacement, sanitized)

        # Basic verification: Ensure standard disclaimers exist if any stock recommendation is found
        buy_sell_triggers = ["buy", "sell", "hold", "invest", "recommendation"]
        normalized = sanitized.lower()
        if any(trigger in normalized for trigger in buy_sell_triggers):
            if "investment advice" not in sanitized and "educational purposes" not in sanitized:
                logger.info("OutputGuardrail: Injecting missing financial disclaimer due to advice keywords.")
                sanitized = (
                    f"{sanitized}\n\n*Disclaimer: This response contains references to stock analysis. "
                    f"This information is for educational purposes and should not be considered financial advice.*"
                )

        return sanitized
